### ISSUE TITLE
checkerboard detection for high-resolution images

### ISSUE THREAD

**Issue by cheny00** [Easonyesheng/CCS#20]
Thank you very much for your work. 
I plan to implement checkerboard detection for high-resolution images (e.g 4000 * 3000). Do you have any suggestions in your work?

As far as I know, synthesizing a dataset requires some modifications. How can I set the approximate range of parameters?
Do you have any suggestions for the backbone network of checkerboard detection in high-resolution images?

**Comment by Easonyesheng** [comment]
If you want to use learning model to detect high-resolution images, I believe the training data also need to be high-resolution images. However, to be honest, synthesizing high-resolution data is difficult (see recent diffusion-based generation work). Since our released code is not specifically designed for that, I suggest you to carefully review the data generation code, which can be a basis for you to develop novel method.
